### ISSUE TITLE
Tela preta depois de X tempo + Reset Bot

### ISSUE THREAD

**Issue by yann-anderson** [sCriptoHelp/spacecrypto-bot#1]
O Bot esta funcionando, estou tendo apenas dois problemas no jogo.

1  - Atualmente meu game fica com uma tela preta no meio da fight, acredito que uma linha de código identificando uma dela toda preta poderia dar um Refresh no navegador, assim ele iniciaria do zero.

2 - O bot entra em loop infinito quando esta selecionando as naves, talvez uma opção para reiniciar o bot resolveria o problema.

Desde já, agradecido.

**Comment by flroexus** [comment]
it does not work for me at all.

**Comment by flroexus** [comment]
what resolution should i use?

**Comment by JacksonLizier** [comment]
Hello, @flroexus  I'm using 1366 x 768

**Comment by JacksonLizier** [comment]
@YannAnder , muito legal saber que esta funcionando. Obrigado pelo seu Report.

1 - Atualmente meu game fica com uma tela preta no meio da fight, acredito que uma linha de código identificando uma dela toda preta poderia dar um Refresh no navegador, assim ele iniciaria do zero.

R: Vou tentar tratar aqui esse problema.

2 - O bot entra em loop infinito quando esta selecionando as naves, talvez uma opção para reiniciar o bot resolveria o problema.

R: Voce limitou a quantidade de naves que ele deve enviar para Lutar?
Essa configuração pode ser feita no "config.yaml" no campo: qtd_send_spaceships

Talves seja isso que esteja criando o Loop infinito.

**Comment by yann-anderson** [comment]
> @YannAnder , muito legal saber que esta funcionando. Obrigado pelo seu Report.
> 
> 1 - Atualmente meu game fica com uma tela preta no meio da fight, acredito que uma linha de código identificando uma dela toda preta poderia dar um Refresh no navegador, assim ele iniciaria do zero.
> 
> R: Vou tentar tratar aqui esse problema.
> 
> 2 - O bot entra em loop infinito quando esta selecionando as naves, talvez uma opção para reiniciar o bot resolveria o problema.
> 
> R: Voce limitou a quantidade de naves que ele deve enviar para Lutar? Essa configuração pode ser feita no "config.yaml" no campo: qtd_send_spaceships
> 
> Talves seja isso que esteja criando o Loop infinito.

Obrigado pelo retorno.

Configurei sim, esta certinho, o loop que esta dando é enquanto ele esta adicionando as naves, ai a tela fica preta ou a pag é atualizada ai ele fica, por exemplo, na nave 11 ai ele fica tentando adicionar a nave 11 infinitamente.

**Comment by JacksonLizier** [comment]
Ola, sub a atualização para tratar o erro da tela preta.
Do loop tente atualizar as Imagens de X e Fight na pasta.

**Comment by yann-anderson** [comment]
> Ola, sub a atualização para tratar o erro da tela preta. Do loop tente atualizar as Imagens de X e Fight na pasta.

Olá, fiz o teste e não funcionou ai tirei um print da minha tela e funcionou mas não sempre, ele deu certo algumas vezes e outras não, saberia o que poderia ser?

**Comment by JacksonLizier** [comment]
tente pegar no print do botao parte da borda, para ver se resolve

**Comment by yann-anderson** [comment]
> tente pegar no print do botao parte da borda, para ver se resolve

1 - Esta funcionando muito bem agora, tela preta esta 100%, único problema agora é que o código em algum momento buga, acho que seria legal fazer igual ao bot do Bomb que dava muito problema e colocaram para reinicializar o bot automaticamente depois de X tempo, acho que é a cada 30 min ou 1h, talvez até por opção de escolher esse tempo.

Veja como fica - https://postimg.cc/SYfG9rDX

2 - A questão que eu tinha comentado de ficar enviando as naves pra lutar infinitamente ocorreu novamente quando deu a tela preta, tem 2 versões diferentes de quando deu tela preta e ele trava, veja como ficou o código - https://postimg.cc/K3YHZjP3 | https://postimg.cc/9zZygCyc

**Comment by JacksonLizier** [comment]
Ola, criado função para reiniciar o jogo em um intervalo de tempo configuravel.
De uma olhadinha no Link: https://github.com/sCryptoHelp/spacecrypto-bot/releases

**Comment by yann-anderson** [comment]
> Ola, criado função para reiniciar o jogo em um intervalo de tempo configuravel. De uma olhadinha no Link: https://github.com/sCryptoHelp/spacecrypto-bot/releases

1 - Opa, eu fiz os testes e esta tudo funcionando, só uma coisa que acho que esta faltando é além de dar F5 no navegador depois de X tempo é ele reiniciar também o BOT, porque algumas vezes ele simplesmente buga,, ai se o bot faz um comando de X em X tempo para abrir novamente e começar do zero esse bug some ao reiniciar tudo (é o que faço manualmente hoje, fecho e abro ele).

2 - Outro detalhe que vi e que não sei se é possível arrumar é a Metamastk, quando vai fazer a assinatura pra entrar no game as vezes não aparece na tela, fica oculto, ai o bot não identifica o ASSINAR, isso pra mim foi resolvido com a atualização que fez do F5 a cada X tempo que colocou, estou usando 30 min pra ele dar F5 na página e enviando apenas as naves em Full, vem funcionando.

**Comment by JacksonLizier** [comment]
1 - Opa, eu fiz os testes e esta tudo funcionando, só uma coisa que acho que esta faltando é além de dar F5 no navegador depois de X tempo é ele reiniciar também o BOT, porque algumas vezes ele simplesmente buga,, ai se o bot faz um co mando de X em X tempo para abrir novamente e começar do zero esse bug some ao reiniciar tudo (é o que faço manualmente hoje, fecho e abro ele).

R: Entao, a funcao deve realizar isso, e mesmo que ele nao conclua, por estar na tela de Login, depois de algum tempinho ele deve começar o ciclor de Login novamente.
Veja aqui a funcao:
   https://github.com/sCryptoHelp/spacecrypto-bot/blob/f67a2848be4bca9e62085780f9848a57b677c714/index.py#L402-L405

E no loop da main() ele fica verificando se esta na tela de Login
   https://github.com/sCryptoHelp/spacecrypto-bot/blob/f67a2848be4bca9e62085780f9848a57b677c714/index.py#L441-L442
  
2 - Outro detalhe que vi e que não sei se é possível arrumar é a Metamastk, quando vai fazer a assinatura pra entrar no game as vezes não aparece na tela, fica oculto, ai o bot não identifica o ASSINAR, isso pra mim foi resolvido com a atualização que fez do F5 a cada X tempo que colocou, estou usando 30 min pra ele dar F5 na página e enviando apenas as naves em Full, vem funcionando.

R: Esse problema sofro no Bomb he he.

Fico feliz que esta Funcionando....

Acompanhe as atualizações no Link: https://github.com/sCryptoHelp/spacecrypto-bot/releases

♥ Se possivel de aquela forcinha. Ficarei muito grato ♥
Wallet Smart Chain: 0xCD1A7A05DC2ee5d0CcB38a4e653e81A4CA78657c
Chave Pix: 8c3b043a-b2c0-44df-a90d-41b3f4294614

**Comment by yann-anderson** [comment]
Testei algumas horas e apresentou ainda alguns bugs, bot trava e da loop ainda, queria saber se poderia fazer o bot dar um refresh nele mesmo? Tipo como se tivesse acabado de abrir? Acho que só falta isso para ficar 100%.

E com certeza farei uma doação pra você assim que puder sacar os SPE, você merece.

**Comment by JacksonLizier** [comment]
Ola! Acredito que consegui chegar em uma solucao para deixar o refreshPage mais rapido.
Criei uma configurção para que possa definir um Tempo em que o bot vai esperar após a tela recarregar.
Seria aquele tempo entre o atualizar e o carregar depois do Cubo.
Fiz alguns teste e cheguei em **30s** aqui na minha conexao. 
Teste ai por favor, caso necessario coloque um intervalo de tempo maior.

https://github.com/sCryptoHelp/spacecrypto-bot/blob/c5e9016e9023b52439674e8dfec6b7171897623a/config.yaml#L221-L229

Veja um Video com o ajuste em execução:

👉 https://youtu.be/sbJnfKI9mcE

**Comment by yann-anderson** [comment]
Eu fiz uns testes durante a madrugada e varios bugs tem ocorrido e **de tudo o que fiz a única coisa que resolve pra  mim é Fechar e Abrir o BOT**, ele executa por um tempo até ficar tela preta (que não esta funcionando atualizar a página na segunda vez que aparece), por isso acredito que uma opção de **resetar o BOT** e não a página com F5 seja a melhor opção.

Nesse link do bot do bomb tem essa opção, eu abro por um .bat que chama o index.py em looping que é o que faz o bot reabrir por cima do outro:
https://github.com/bnudaniel22/bombcrypto-bot/archive/refs/heads/main.zip

OBS: Nessa att nova de escolher a quantidade de nave a ser enviada e a quantidade mínima não funcionou pra mim nos testes que fiz. Essa ideia que teve é perfeita, pois tenho 38 naves e coloquei pra enviar 13 e se não tiver 13 ele envia 12, assim enviaria 100% das naves certinho, porém não ta rolando aqui.

**Comment by JacksonLizier** [comment]
Opa Mestre, vou olhar o Arquivo enviado.
Das funcoes novas, subi algumas atualizações.

Esta funcionando?

**Comment by yann-anderson** [comment]
Não cheguei a testar, coloquei outro improvisado aqui que esta parcialmente funcionando, farei os testes hoje e retorno.

**Comment by yann-anderson** [comment]
Vamos lá, testei 3 bots, o seu até agora foi o melhor, com mais configurações e que melhor se adéqua a diversas realidades, porém acredito que para ficar perfeito precisaria considerar algumas questões que acredito ser simples de resolver.

1 - A opção de refresh page por tempo não foi efetivo, eu desconsiderei ela.

2 - A opção de erro da Tela Preta não funciona de fato, se funcionasse 100% não teria mais nenhum problema para resolver.

3 - Opção de refresh depois de X tempo aparecendo mensagem de erro do BOT "Nenhuma acao encontrada", essa opção foi implementada em um dos bots que testei, sempre que o bot não enxerga alguma imagem ele fica dando erro repetidamente informando "Nenhuma acao encontrada", no código o rapaz colocou se aparecer a mensagem "Nenhuma acao encontrada" ele da refresh depois de X tempo (eu uso 90 segundos) - Link do ajuste do Bot que testei https://github.com/cryptotwinsbr/spacecrypto-bot/pull/29/commits/59751f99d60228f4e8662ddf7070d723e91c8ec9.

Esse item 3 funcionou muito bem até mesmo com o server fora do ar quando estava em manutenção, ele sempre atualizava a página buscando imagens e quando aparecia voltava a jogar normalmente (eu trocaria a opção CTFL+F5 para SHIFT+CTRL+R ou dar a opção da pessoa escolher entre as duas igual tem em um dos bots que testei)

Acho que é isso, espero que meu feedback também ajude muitas outras pessoas e que elas possam fazer doações para você também.

**Comment by JacksonLizier** [comment]
@YannAnder , obrigado pelo Feedback.
Ajudou muito sim! todos o Feedback é sempre bem vindo.
Sub na branches Desenvolvimento algo aqui seguindo essa ideia sugerida.
Estou acompanhando para ver se vai ficar ok e na sequencia publico em produção.

Sobre as doações, ta tenso he he, pessoal esta pagando para ter acesso a codigos similares a esse que estou disponbilizando.
Caso queira acompanhar minha carteira: https://debank.com/profile/0xcd1a7a05dc2ee5d0ccb38a4e653e81a4ca78657c

**Comment by JacksonLizier** [comment]
@YannAnder, funcoes aplicadas.
Deixei executando 7h sem parar.

Caso queira acompanhar o bot em execução em minha maquina estou tentando manter em Live o maior tempo possivel: https://www.twitch.tv/jacksonlizier?sr=a

**Comment by yann-anderson** [comment]
> @YannAnder, funcoes aplicadas. Deixei executando 7h sem parar.
> 
> Caso queira acompanhar o bot em execução em minha maquina estou tentando manter em Live o maior tempo possivel: https://www.twitch.tv/jacksonlizier?sr=a

Baixando agora mesmo, vou testar e dou um retorno.

**Comment by yann-anderson** [comment]
Man, não funcionou, por algum motivo ele trava na tela inicial de carregamento sempre que atualiza, não sei se é bug ou o que, estou usando um outro, é mais simples, mas funciona pra mim.

Agradecido por tudo, espero que a moeda recupere para tirarmos nosso ROI e eu poder te dar um pouco como forma de agradecimento.
