### ISSUE TITLE
O bot não inicia

### ISSUE THREAD

**Issue by jeffersonmdias** [sCriptoHelp/spacecrypto-bot#10]
Já instalei tudo certinho, inclusive rodo outros bots no meu pc para space normalmente, mas estava querendo testar o seu para ver se é mais eficiente que o que estou usando atualmente, porém ele n sai dessa parte.

```
>>---> Pressione ctrl + c para parar o bot.


←[99m[2022-02-20 12:26:42] => ⬆️ Processing last action..←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.
```

**Comment by JacksonLizier** [comment]
Ola
Abra o jogo na tela das naves, inicie o bot.
Deixe o Jogo em 1 plano e acompanhe se ele vai clicar nas naves que estiverem com o botão **“Fight”** vermelho. 
Se ele não clicar, tente substituir a imagem “spg-go-fight.png” ![](https://github.com/sCryptoHelp/spacecrypto-bot/blob/main/targets/spg-go-fight.png?raw=true) localizada dentro da pasta “targets” e repita o teste.

Caso funcione será necessário _substituir as demais imagens_ que estão na pasta.

Caso mesmo assim não funcione, desinstale o Phyton e apague a pasta localizada no **“C:\Program Files\Python310”** e repita o processo de Instalação seguindo o passo a passo disponível nesse link: [https://youtu.be/L1CkRyTmpxM](https://youtu.be/L1CkRyTmpxM)

Veja se resolve
