### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by alexbatista26** [sCriptoHelp/spacecrypto-bot#11]
Sem suporte para linux?

**Comment by JacksonLizier** [comment]
Ola, posso tentar ajudar.
Como o bot segue a mesma estrutura do utilizado por muitos no bombcrypto, deve fucionar sim.
Faça o seguinte.
Tente seguir esse passo a passo: https://www.youtube.com/watch?v=2w4yBtFjGaA&list=PL7cXxKmkGPa7A5xGYOW_buE8wW2QwIJZv&index=17

Porem utilizando os arquivos do Bot para o SPG.

Me avise se conseguir ou não conseguir para que possamos tentar ver uma forma de ser possivel a utilização em Linux.

**Comment by quasemago** [comment]
Linux não possui suporte a lib `pygetwindow`, removi isso no meu fork e estou rodando tranquilamente no ubuntu, visto que não tem uma utilidade importante no código.

**Comment by JacksonLizier** [comment]
@quasemago, Vlw a Dica.. ja apliquei aqui.

**Comment by quasemago** [comment]
@JacksonLizier Faltou remover a lib `PyGetWindow `do **requirements**, pois vai dar erro na hora de instalar no ubuntu/linux.

**Comment by JacksonLizier** [comment]
@quasemago , muito bem lembrado! Obrigado pelo retorno.
