### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by therapyofcoffee** [sCriptoHelp/spacecrypto-bot#15]
Não estou conseguindo fazer funcionar no ubuntu, quando dou o comando para iniciar `python3 forever.py index.py` retorna esse erro "Starting index.py
/bin/sh: 1: python: not found"

**Comment by JacksonLizier** [comment]
Ola,
não sei como lhe ajudar pois uso windows.
De uma olhada nesse Link, como o bot é baseado no codigo do Bot do bombcrypto, veja se tem algum detalhe na instalacao que lhe ajude a resolver o problema.
https://www.youtube.com/watch?v=2w4yBtFjGaA&list=PL7cXxKmkGPa7A5xGYOW_buE8wW2QwIJZv&index=17

**Comment by therapyofcoffee** [comment]
Funcionou depois de instalar `sudo apt-get install python3-tk python3-dev
` e o pip, e executando somente o index `python3 index.py`

**Comment by JacksonLizier** [comment]
@therapyofcoffee  show! Apliquei alguns ajustes... de uma olhadinha : )
Bom Farm !
