### ISSUE TITLE
Não reseta o Boss

### ISSUE THREAD

**Issue by marcosfecrypto** [sCriptoHelp/spacecrypto-bot#2]
Boa tarde!

Primeiramente obrigado pela disponibilização do código! Assim que liberar o Claim terá minha pequena contribuição! ^^

Gostaria de entender em qual momento que é feito o Reset do Boss através do Botão Surrender, e também, em qual momento que volta para o Menu Principal para repor as naves.

Pois neste momento, mesmo substituindo todas as imagens, o Bot esta apenas colocando as naves para trabalhar (conforme a quantidade que configurei) e vai para a luta com o Boss e fica nisso.

Obrigado!

**Comment by blazeBR** [comment]
Estou passando pela mesma situação

**Comment by JacksonLizier** [comment]
Ola, o reset é feito quando a vida do boss fica muito tempo de se mover.
Enviei algumas atualizações para ser possivel configurar o momento de Resert do Boss, onde é possivel definir a Wave.

**Comment by JacksonLizier** [comment]
Ola, o problema ainda ocorre?
