### ISSUE TITLE
Não executa

### ISSUE THREAD

**Issue by GCarin1** [sCriptoHelp/spacecrypto-bot#3]
ele só fica na tela inicial nem um outra função executa dentro de minutos, e todas os requerimentos estão instalados e não deu erro qualquer na execução, ele só não faz as ações

**Comment by rogeriojim** [comment]
up

**Comment by JacksonLizier** [comment]
Ola, 
deixe o bot na tela das naves para ver se ele inicia.

**Comment by falpz** [comment]
mesma coisa aqui

**Comment by JacksonLizier** [comment]
Ola, algumas coisas que podem ser testadas:

 - Mude a resolsução para 1366 x 768
 - Tire um print de sua tela e substitua as imagens na pasta targets. Porem cuido ao substituir as imagens.
 Mantenha os mesmo nomes.png
 
 Qualquer coisa me chame no Telegram: @JacksonLizier

**Comment by JacksonLizier** [comment]
Ola, o problema ainda ocorre?

**Comment by Mauriciojrx** [comment]
Aqui deu o mesmo problema, porem foi do nada, ele tava funcionando normal, parei pra mexer no pc, qndo fui ligar dnv o bot, ele nao faz nada, so faz movimento se a tela do cmd estiver em primeiro plano, mas ai ele n clica no jogo tbm, as vezes ate aparece que enviou naves, mas sequer se mexeu, ja reinstalei ele, reinstalei o python e nada

**Comment by GCarin1** [comment]
@Mauriciojrx  substitui as imagens novamente que volta ao normal

**Comment by JacksonLizier** [comment]
@GCarin1  sua resposta me deu uma ideia.... Muito obrigado pela colaboração...
 Vou pedir para quem puder enviar as imagens que estao utilizando zipadas e a resolução.
 E vou criar um repositorio com todos que eu for recebendo!
 
 \o/

**Comment by GCarin1** [comment]
@JacksonLizier não sei se só isso resolveria esse problema de resolução, alguns prints já estão na resolução, por exemplo o meu é de 1920 e mesmo prints tirados nessa resolução em outros  monitores ainda dão essa falha

**Comment by JacksonLizier** [comment]
Entendi, muito obrigado pelo retorno.
Bom, vou tentar coletar algumas resolucoes e deixar disponivel. 
Pode ser que não resolva 100% mas ja deve ajudar um pouco o pessoal que ainda não conseguil pegar a ideia de como atualizar as imagens.

**Comment by Mauriciojrx** [comment]
> @Mauriciojrx  substitui as imagens novamente que volta ao normal

Eu fiz, mudei todas, fui mudando de uma em uma, nada, reiniciei a maquina e nada, ai do nada, da mesma forma que parou, voltou

**Comment by JacksonLizier** [comment]
@Mauriciojrx , kkkkkk 
O codigo de vida propria... : p

**Comment by Mauriciojrx** [comment]
> @Mauriciojrx , kkkkkk 
> O codigo de vida propria... : p

Pois eh, acho que era cansaço kkkkkkk
