### ISSUE TITLE
Bot fica indo para tela de naves

### ISSUE THREAD

**Issue by sim-lipotril** [sCriptoHelp/spacecrypto-bot#4]
Bot fica indo para a tela de naves e selecionando as naves, sendo que já tem 15 naves para atacar. Ele faz esse processo e depois de colocar novamente o que já estava, não demora muito tempo e ele já vai para a tela de selecionar as naves novamente.

**Comment by sim-lipotril** [comment]
![image](https://user-images.githubusercontent.com/96153507/154392532-14c5c042-1bf6-4158-bedb-bc359f4eef4f.png)
Uma boa tbm seria verificar as naves se estão indisponíveis e após isso clicar para selecionar novas naves.

**Comment by sim-lipotril** [comment]
![image](https://user-images.githubusercontent.com/96153507/154392784-91681111-8c5a-4527-b656-3f0d060a8632.png)
Isso é algo que está atrapalhando tbm. Diz que já selecionou as 15, mas na verdade não selecionou. Consegue colocar algo que verifica a quantidade de naves pela imagem? que ai só mandaria quando estivesse 15/15

**Comment by JacksonLizier** [comment]
Ola,  acesse as configurações e coloque mais tempo no parametro de check_boss, ele deve estar entendendo que a vida do boss nao esta baixando e voltando para refazer o processo.
Da contagem das naves ainda não conseguir fazer algo preciso, pois estou contando os click considerando que foram selecionadas, vou trabalhar para melhorar um pouco.
Das naves que morreram, eu tentei fazer essa leitura das naves com um X sobre elas, porem observer que as vezes o jogo buga e elas morrem se não marca um X.
Por isso eu fico olhando a vida do boss em intervalos, se ela não baixar subentende que não tem mais naves atacando.

Obrigado pelo Feedback.

**Comment by sim-lipotril** [comment]
Na leitura das naves, creio que além dos clicks você poderia colocar algo para verificar a imagem 15/15 que é de quando todas as 15 foram selecionadas.

O jogo está meio travado então essa parte de selecionar as naves tem que demorar mais.

**Comment by sim-lipotril** [comment]
Essas imagens life boss 1,2 e 3 do que seriam basicamente e em que momento essas fotos foram tiradas? Tentei ver em relaçao a vida do boss mas não consigo identificar certinho para tirar novas fotos. Poderia mostrar uma foto em tamanho real qual seria o momento das prints para eu poder atualizar?

**Comment by JacksonLizier** [comment]
Ola, tem a funcao lifeBoss() que retorna qual a ultima posição o bot identifica alguma dessas 3 imagens.
Eu criei 3 imagens pq a barra no começo é torta e como tem os efeitos visual precisei separar.
Depois que a vida do boss começa baixar segue um padrao da barra so ficar vermelha igual na Imagem spg-life-boss-2.
Ele fica olhando a tela toda na funcao positions(), que retorna a posição que tem a Imagens que passo para ela.

: )

**Comment by JacksonLizier** [comment]
Ola, conseguil validar se ficou Ok?
Se conseguir dar um retorno para fechar a Issues.

: )
