### ISSUE TITLE
Surrender is clicked when type_limit_wave: 'EndFight'

### ISSUE THREAD

**Issue by flroexus** [sCriptoHelp/spacecrypto-bot#5]
Surrender is clicked when type_limit_wave: 'EndFight'

**Comment by JacksonLizier** [comment]
Hello, yes, This Idea is to return to the first boss.

**Comment by flroexus** [comment]
I see, I was expecting it to go back to ships then deploy new set of ships. Tnx. What settings to set to deploy more ships while maintaining the current stage
"Define here if at the end of the Wave Limit the bot should end the fight and reload the ships or just Surrender"

**Comment by JacksonLizier** [comment]
Hello, I changed the function

Options: EndFight - Only Renew ships 
              Surrender - Only Surrender 
              EndFightAndSurrender - Renew ships and Surrender - Retur to first boss

**Comment by flroexus** [comment]
perfect,. basically it renew ships according to set wave, right?

**Comment by JacksonLizier** [comment]
Yes : )
