### ISSUE TITLE
end of wave return selection

### ISSUE THREAD

**Issue by druidou41** [sCriptoHelp/spacecrypto-bot#6]
Hello, great work! ! !
at the end of each wave the BOT returns to the selection of ships, removes the ships then replaces them is this normal? Is there an option to change to avoid this?

**Comment by JacksonLizier** [comment]
Hello,
yes.. This idea is to remove ships which less life and put new ships.
Have three options if you use the limit of wave:

EndFight - Only Renew ships
Surrender - Only Surrender
EndFightAndSurrender - Renew ships and Surrender - Return to the first boss
