### ISSUE TITLE
Hotkey para dar refresh na pagina

### ISSUE THREAD

**Issue by quasemago** [sCriptoHelp/spacecrypto-bot#7]
https://github.com/sCryptoHelp/spacecrypto-bot/blob/main/index.py#L153:

utilizar
`pyautogui.hotkey('ctrl','f5')`
em vez de:
`clickBtn(images['refresh-page'])`

dessa forma não importa a cor do navegador

**Comment by JacksonLizier** [comment]
Ola, vou tentar usar novamente esse comando, eu havia tentando mas ele n funcinou para mim.
Assim que eu aplicar retorno.

Obrigado pelo Feedback

**Comment by JacksonLizier** [comment]
\o/  Deu Certo!!!!!

Ja publiquei a atualização.

https://github.com/sCryptoHelp/spacecrypto-bot/blob/main/index.py#L154

Muito Obrigado!!!
