### ISSUE TITLE
Bot mata 1 wave e já volta para selecionar novas naves

### ISSUE THREAD

**Issue by sim-lipotril** [sCriptoHelp/spacecrypto-bot#8]
A cada wave que o bot destroi ele fica voltando para selecionar as naves sendo que estão todas cheias. Como resolvo isso?

**Comment by JacksonLizier** [comment]
Ola, consegue validar qual o valor que esta no arquivo config.yaml
campos: 
limit_wave: ???
qtd_limit_wave: ???

outra coisa,
Mude o check_boss para 10 ou +.
Talves esteja demorando baixar a vida do boss e dando um falso positivo que nao tem naves atacando ele.

**Comment by JacksonLizier** [comment]
Ola, o problema ainda ocorre?

**Comment by sim-lipotril** [comment]
Não tinha visto que havia respondido. Sim, ainda ocorre. A cada nave que destrói, ele volta para selecionar as naves. E seleciona 15 naves, mesmo já tendo 15 naves

**Comment by JacksonLizier** [comment]
@sim-lipotril , me  chame no Telegem @JacksonLizier, para que eu possa tentar acompanhar e ver o que pode estar ocorrendo.
