### ISSUE TITLE
É possivel MultAccount?

### ISSUE THREAD

**Issue by evertonurbanii** [sCriptoHelp/spacecrypto-bot#9]
É possivel MultAccount? Ou tem alguma previsão para implantação?

**Comment by JacksonLizier** [comment]
Ola, direto pelo bot ainda não é possivel.
Não tenho mais de uma Acc para testar  e desenvolver algo que atenda essa necessidade.

Mas foi postado um Video muito TOP explicado uma forma que pode ajudar a rodar MultAcc: 

https://www.youtube.com/watch?v=avBwVOA7HCU

: )

♥ Se possivel de aquela forcinha. Ficarei muito grato - Ai abro uma nova Acc para desenvolver alguma rotina MultAcc ♥
Wallet Smart Chain: 0xCD1A7A05DC2ee5d0CcB38a4e653e81A4CA78657c
Chave Pix: 8c3b043a-b2c0-44df-a90d-41b3f4294614
